import { Clock, Wallet, CalendarDays, LayoutGrid, Target, GitBranch, Sparkles, MessageSquare, Bell, Activity, Video, PenTool, Users, UserPlus, Briefcase, FileText } from 'lucide-react';

export const categories = ['All features', 'Daily work', 'People & HR', 'MIRA & insights'] as const;
export type ProductFeature = {
  slug: string; name: string; category: typeof categories[number]; icon: typeof Clock;
  eyebrow: string; headline: string; description: string; note: string;
  capabilities: [string, string][]; flow: [string, string][];
  preview: 'board' | 'conversation' | 'records'; rows: [string, string, string][];
};
export const productFeatures: ProductFeature[] = [
  {
    slug: 'projects', name: 'Projects & tasks', category: 'Daily work', icon: LayoutGrid,
    eyebrow: 'A place for the work', headline: 'Know what’s moving.\nAnd what needs a hand.',
    description: 'Give each project a team, a timeline and a clear next step. Keep tasks, notes and updates close to the work they belong to.',
    note: 'Project visibility and approval actions depend on your role and membership.',
    capabilities: [['Make ownership clear', 'Assign project heads and members, give tasks a priority, and set due dates.'], ['Keep the context', 'Use project notes, task conversations and activity history to explain what changed.'], ['Follow work through review', 'Track task status and project completion approvals without losing the original request.']],
    flow: [['Plan it', 'Create a project and invite the people doing the work.'], ['Work on it', 'Break it into tasks with owners and dates.'], ['Review it', 'Check progress and follow up on pending approvals.']],
    preview: 'board', rows: [['Outline the launch', 'Planning', 'Brief ready'], ['Review the first draft', 'In progress', 'Team review'], ['Share the final assets', 'Complete', 'Approved']],
  },
  {
    slug: 'MIRA-ai', name: 'MIRA assistant', category: 'MIRA & insights', icon: Sparkles,
    eyebrow: 'Ask. Find. Get something done.', headline: 'A little less searching.\nA little more doing.',
    description: 'Talk or type to MIRA inside Talio. Find a project, create a task, arrange a meeting or get help making sense of your work.',
    note: 'MIRA uses your access permissions. AI output needs review; voice, screen tools and image features depend on device support, permissions and provider availability.',
    capabilities: [['Turn a request into an action', 'Create tasks, projects and meetings, assign work, and send a message when you ask.'], ['Stay in the conversation', 'Use voice, a compact view, quick notes and personal reminders as you move through Talio.'], ['Bring in context', 'Ask about accessible work, attach supported files, or request help navigating the current app view.']],
    flow: [['Ask naturally', 'Describe what you need in text or voice.'], ['Fill in the gaps', 'MIRA asks for missing details or helps resolve a name.'], ['Check the outcome', 'See the result of the action and open the related work.']],
    preview: 'conversation', rows: [['You', 'Find the launch project.', 'Request'], ['MIRA', 'Which launch project do you mean?', 'Clarify'], ['You', 'The website launch. Open its tasks.', 'Continue']],
  },
  {
    slug: 'productivity', name: 'Productivity insights', category: 'MIRA & insights', icon: Activity,
    eyebrow: 'Context for your working day', headline: 'Review the day.\nUnderstand the work.',
    description: 'Bring activity, captured screens and MIRA summaries into a daily view. Explore a date or an accessible team member when you need more context.',
    note: 'Desktop capture requires permissions and company configuration. Activity and AI summaries are context for a conversation, not proof of the quality of someone’s work.',
    capabilities: [['Look at a specific day', 'Choose a date and review the activity and captures available for it.'], ['Inspect the evidence', 'Open captured screens and move through a gallery rather than relying only on a summary.'], ['Use MIRA for a first pass', 'Request analysis of available captures and review the result alongside the source material.']],
    flow: [['Set up capture', 'Install the desktop app and follow your company’s permission setup.'], ['Choose a view', 'Look at your day or the team data your role can access.'], ['Review in context', 'Use the underlying captures to check AI observations.']],
    preview: 'records', rows: [['Daily activity', 'Selected day', 'Review'], ['Screen captures', 'Available captures', 'Open gallery'], ['MIRA summary', 'Review with context', 'Insights']],
  },
  {
    slug: 'attendance', name: 'Attendance', category: 'People & HR', icon: Clock,
    eyebrow: 'Start with a clear record', headline: 'Check in. Get on\nwith your day.',
    description: 'Record check-ins and check-outs, review attendance, and request corrections when something is missing. Location rules help match attendance to your workplace.',
    note: 'Location permissions and company geofence rules apply. Machine attendance requires a supported device and a configured integration.',
    capabilities: [['Check in with context', 'Use location-aware attendance and configured office boundaries.'], ['Correct a missed entry', 'Submit regularisation requests for a manager to review.'], ['See the record', 'Review attendance reports, check-in history and team attendance from the views available to your role.']],
    flow: [['Check in', 'Allow location access where your company requires it.'], ['Check your record', 'See your working day and check-out status.'], ['Resolve exceptions', 'Request a correction and follow its approval.']],
    preview: 'records', rows: [['Morning check-in', 'Office location', 'Recorded'], ['Missing check-out', 'Correction requested', 'Pending'], ['Attendance report', 'Selected month', 'Review']],
  },
  {
    slug: 'leaves', name: 'Leave & availability', category: 'People & HR', icon: CalendarDays,
    eyebrow: 'Make room for life', headline: 'Time off,\nwithout the back-and-forth.',
    description: 'Request leave, check your balance and follow approvals in one place. Keep work-from-home and early-leave requests alongside your attendance routines.',
    note: 'Leave types, allocations and approval rules are set by your company.',
    capabilities: [['Know what’s available', 'See leave balances and company allocations before making a request.'], ['Make a clear request', 'Choose dates, a leave type and the information your approver needs.'], ['Keep decisions visible', 'Review requests and track approval status, including WFH and early leave.']],
    flow: [['Check your balance', 'Review the leave available to you.'], ['Send a request', 'Add dates and a reason.'], ['Follow the decision', 'See whether it is pending, approved or rejected.']],
    preview: 'records', rows: [['Annual leave', 'Dates selected', 'Approved'], ['Work from home', 'Awaiting review', 'Pending'], ['Leave balance', 'Current allocation', 'View']],
  },
  {
    slug: 'payroll', name: 'Payroll & payslips', category: 'People & HR', icon: Wallet,
    eyebrow: 'A clearer monthly routine', headline: 'From payroll records\nto a payslip you can find.',
    description: 'Prepare payroll with employee salary details, attendance inputs and deductions. Review the records and make payslips available to employees.',
    note: 'Payroll depends on your salary setup and applicable rules. Talio records and calculations do not replace payroll review, statutory filing or bank disbursement.',
    capabilities: [['Prepare the period', 'Generate payroll records for a selected month and year, including bulk processing.'], ['Review the details', 'Check earnings, deductions and payroll status before completing your process.'], ['Find a payslip', 'Employees can access the payslips available to them.']],
    flow: [['Set up employee details', 'Keep salary and payroll information current.'], ['Generate and review', 'Check the period’s payroll records.'], ['Share the record', 'Make the resulting payslip accessible.']],
    preview: 'records', rows: [['Payroll period', 'Month selected', 'Prepared'], ['Earnings & deductions', 'Review inputs', 'Review'], ['Employee payslip', 'Payroll record', 'Available']],
  },
  {
    slug: 'goals', name: 'Goals & performance', category: 'People & HR', icon: Target,
    eyebrow: 'Give progress some direction', headline: 'Make the goal clear.\nKeep the conversation going.',
    description: 'Set goals, update progress and bring performance reviews into one place. Give managers and employees something concrete to discuss.',
    note: 'Goal management, ratings and performance views are controlled by role and company settings.',
    capabilities: [['Set a goal', 'Create goals with the details and dates that define the work.'], ['Review progress', 'Update goals and look back at their status.'], ['Connect the discussion', 'Use performance ratings and reports alongside task and attendance context.']],
    flow: [['Agree on the goal', 'Describe the outcome and set a time frame.'], ['Keep it current', 'Update progress as work moves forward.'], ['Review together', 'Use the record to support a performance conversation.']],
    preview: 'records', rows: [['Improve onboarding', 'Team goal', 'In progress'], ['Review the handover', 'Next check-in', 'Scheduled'], ['Performance review', 'Current period', 'Draft']],
  },
  {
    slug: 'workflows', name: 'Requests & approvals', category: 'People & HR', icon: GitBranch,
    eyebrow: 'Know where things stand', headline: 'Less “who has this?”\nMore clear next steps.',
    description: 'Follow the requests that move people and work forward: attendance corrections, leave, project completion and employee lifecycle steps.',
    note: 'These are Talio’s supported approval flows. Available steps depend on the module, your role and your company’s setup.',
    capabilities: [['Bring requests into the process', 'Use the relevant attendance, leave, project or people flow to submit work for review.'], ['Keep the decision attached', 'Review status, comments and recorded actions in the context of the request.'], ['Move to the next step', 'Track onboarding, probation and offboarding steps within employee operations.']],
    flow: [['Submit', 'Provide the information needed for a decision.'], ['Review', 'The authorised person reviews the request.'], ['Follow through', 'Check the outcome and continue the process.']],
    preview: 'records', rows: [['Leave request', 'Submitted by employee', 'Pending'], ['Project completion', 'Reviewed by project head', 'Approved'], ['Probation review', 'Employee lifecycle', 'Next step']],
  },
  {
    slug: 'team-chat', name: 'Team chat', category: 'Daily work', icon: MessageSquare,
    eyebrow: 'A conversation, close to the work', headline: 'Ask the quick question.\nKeep your place.',
    description: 'Message a teammate or bring a group together. Desktop chat popups let you keep the conversation open while you work elsewhere in Talio.',
    note: 'Chat access follows company membership and feature settings. Delivery and presence depend on connectivity.',
    capabilities: [['Talk one-to-one or as a group', 'Start a private conversation or create a group with colleagues.'], ['Share the details', 'Send files, mention teammates and react to messages.'], ['Keep work in view', 'Use floating conversations on desktop and the dedicated chat view on mobile.']],
    flow: [['Find your people', 'Choose a colleague or a group.'], ['Share the context', 'Write a message or attach a file.'], ['Carry on working', 'Keep the conversation nearby as you move through Talio.']],
    preview: 'conversation', rows: [['Design team', 'The updated brief is ready to review.', 'Message'], ['You', 'Thanks. I’ll add my notes to the project.', 'Reply'], ['Design team', 'Perfect, let’s keep the feedback there.', 'Follow-up']],
  },
  {
    slug: 'meetings', name: 'Meetings', category: 'Daily work', icon: Video,
    eyebrow: 'Before, during and after', headline: 'Meet with a plan.\nLeave with context.',
    description: 'Schedule a meeting, invite the right people and keep the agenda nearby. Online meeting tools and MIRA summaries help you return to what was discussed.',
    note: 'Online calls need camera or microphone permissions as appropriate. Summaries need available transcript or notes and an AI provider; review them for accuracy.',
    capabilities: [['Arrange the meeting', 'Choose a time, agenda and attendees for an online or offline meeting.'], ['Join the conversation', 'Use Talio’s online meeting room and supported screen-sharing tools.'], ['Return to the discussion', 'Generate or refresh a MIRA summary from the transcript and notes available.']],
    flow: [['Schedule', 'Set the agenda and invite attendees.'], ['Meet', 'Join online or use the offline location details.'], ['Follow up', 'Review the summary and carry decisions into your work.']],
    preview: 'records', rows: [['Weekly planning', 'Agenda & attendees', 'Scheduled'], ['Meeting room', 'Audio, video & sharing', 'Join'], ['Meeting summary', 'From notes or transcript', 'Review']],
  },
  {
    slug: 'whiteboard', name: 'TalioBoard', category: 'Daily work', icon: PenTool,
    eyebrow: 'Space to think together', headline: 'Get the idea\nout of your head.',
    description: 'Use TalioBoard to sketch, arrange ideas and work through a plan on a shared canvas. Keep your boards within the same workspace as your team.',
    note: 'Board access and collaboration depend on membership, connectivity and enabled features.',
    capabilities: [['Start with a canvas', 'Create a board and organise ideas visually.'], ['Work with others', 'Use the board’s collaboration tools to develop an idea together.'], ['Get help from MIRA', 'Use the board’s MIRA sidebar when you need help developing your thinking.']],
    flow: [['Open a board', 'Give your idea a place to begin.'], ['Explore it', 'Sketch and organise the pieces.'], ['Keep the context', 'Return to the board as the work develops.']],
    preview: 'board', rows: [['The idea', 'Explore', 'What are we solving?'], ['The approach', 'Connect', 'What could work?'], ['The next step', 'Decide', 'What do we try first?']],
  },
  {
    slug: 'people', name: 'People & lifecycle', category: 'People & HR', icon: Users,
    eyebrow: 'From the first day onwards', headline: 'People details.\nWith the next step attached.',
    description: 'Keep employee profiles, reporting relationships and lifecycle tasks together, from onboarding and probation to offboarding.',
    note: 'Lifecycle steps are configured by company and role. Some HR modules need additional setup before they can be used.',
    capabilities: [['Keep a useful directory', 'Find employee profiles, departments, designations and reporting relationships.'], ['Support the first weeks', 'Follow onboarding checklists and probation review decisions.'], ['Handle the handover', 'Track offboarding steps, asset clearance and settlement information.']],
    flow: [['Add the employee', 'Set up their profile and place in the team.'], ['Follow the milestones', 'Complete onboarding and review probation.'], ['Keep records current', 'Manage changes and the eventual handover.']],
    preview: 'records', rows: [['Employee profile', 'Department & reporting line', 'Current'], ['Onboarding checklist', 'Joining tasks', 'In progress'], ['Probation review', 'Approver assigned', 'Upcoming']],
  },
  {
    slug: 'recruitment', name: 'Recruitment', category: 'People & HR', icon: UserPlus,
    eyebrow: 'Keep the hiring story together', headline: 'From an open role\nto a new teammate.',
    description: 'Manage roles, candidates and interviews in Talio. Keep hiring progress visible and carry selected candidates into employee onboarding.',
    note: 'Recruitment permissions and enabled modules apply. External recruiting integrations require separate configuration.',
    capabilities: [['Manage open roles', 'Create and filter job records by status, department and employment type.'], ['Follow candidates', 'Maintain candidate records and move them through the hiring process.'], ['Coordinate the next step', 'Schedule interviews and convert a selected candidate into an employee record.']],
    flow: [['Define the role', 'Add the job and its requirements.'], ['Review candidates', 'Keep candidate information and interviews together.'], ['Prepare for joining', 'Carry the selected person into employee setup.']],
    preview: 'board', rows: [['Applications', 'Review', 'Candidate records'], ['Interviews', 'Discuss', 'Interview schedule'], ['Joining', 'Prepare', 'Employee setup']],
  },
  {
    slug: 'operations', name: 'Assets & helpdesk', category: 'People & HR', icon: Briefcase,
    eyebrow: 'The practical side of work', headline: 'Track the equipment.\nFollow the request.',
    description: 'Keep asset records and employee support requests out of scattered spreadsheets and messages. Find the item, the issue and its current status.',
    note: 'Asset management and helpdesk access depend on your company’s enabled modules and your role.',
    capabilities: [['Maintain an asset register', 'Create, update and import asset records for your organisation.'], ['Keep support in one thread', 'Create helpdesk tickets and add comments as an issue is handled.'], ['Remember the return', 'Use asset clearance alongside offboarding so equipment is part of the handover.']],
    flow: [['Record it', 'Add an asset or describe a support issue.'], ['Keep it updated', 'Track the record and its status.'], ['Close the loop', 'Resolve the ticket or complete the asset handover.']],
    preview: 'records', rows: [['Work laptop', 'Employee assignment', 'Assigned'], ['Access request', 'Helpdesk conversation', 'Open'], ['Asset return', 'Offboarding checklist', 'Review']],
  },
  {
    slug: 'documents', name: 'Documents & policies', category: 'People & HR', icon: FileText,
    eyebrow: 'A place to come back to', headline: 'Find the document.\nKnow which policy applies.',
    description: 'Keep company documents and policy information in Talio, alongside the employee workflows that need them.',
    note: 'Document visibility, upload permissions and available policies depend on company configuration.',
    capabilities: [['Store the record', 'Upload and organise documents in the company workspace.'], ['Find shared information', 'Use the documents and policies pages to return to the information you need.'], ['Support people processes', 'Keep employee lifecycle records and supporting documents in the same system.']],
    flow: [['Add the information', 'Upload the relevant document or policy.'], ['Make it accessible', 'Use the visibility available to your role.'], ['Return when needed', 'Find it from the workspace rather than an old message.']],
    preview: 'records', rows: [['Employee handbook', 'Company document', 'Available'], ['Leave policy', 'Company rules', 'Read'], ['Joining documents', 'Employee record', 'Review']],
  },
  {
    slug: 'notifications', name: 'Notifications', category: 'Daily work', icon: Bell,
    eyebrow: 'Stay in the loop', headline: 'The updates\nthat bring you back.',
    description: 'Keep track of work updates, requests and reminders inside Talio. Use your notification preferences to choose how you hear about them.',
    note: 'Push delivery needs a supported device and notification permission. Reminder timing depends on processing and connectivity.',
    capabilities: [['See work updates', 'Receive notifications associated with messages, tasks and people workflows.'], ['Follow requests', 'Open actionable updates and respond where your role allows.'], ['Set your preferences', 'Manage notification settings and use MIRA to schedule a personal reminder.']],
    flow: [['Choose your settings', 'Enable the notifications you want to receive.'], ['Get the update', 'See the event in your notification feed.'], ['Return to the work', 'Open the related request or conversation.']],
    preview: 'records', rows: [['Task assigned', 'Website launch', 'New'], ['Leave request', 'Ready for review', 'Pending'], ['Personal reminder', 'Check the draft', 'Scheduled']],
  },
];
export function getProductFeature(slug: string) { return productFeatures.find(feature => feature.slug === slug); }
